export default listData = [
  {
    id: 1,
    profileLogo: require('../../assets/Images/Jpeg/venue-logo.jpg'),
    pubName: 'Comedy Night',
    uploadTime: '2 days ago',
    place: 'The Venue, Manchester',
    date: 'Sat 15th Aug at 8pm',
    accepted: '2/2',
    exactDate: 'Sat 15th Aug',
    status: 'All set!',
    time: 'From 8pm to 11pm',
    description:
      ' Lorem ipsum dolor sit amet, consetetur sadipscing elitr, seddiam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et',
  },
  {
    id: 2,
    profileLogo: require('../../assets/Images/Jpeg/venue-logo.jpg'),
    pubName: 'Comedy Night',
    uploadTime: '3 days ago',
    place: 'The Venue, Manchester',
    date: 'Sat 15th Aug at 8pm',
    accepted: '0/2',
    exactDate: 'Sat 15th Aug',
    status: 'Recruiting',
    time: 'From 8pm to 11pm',
    description:
      ' Lorem ipsum dolor sit amet, consetetur sadipscing elitr, seddiam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et',
  },
  {
    id: 3,
    profileLogo: require('../../assets/Images/Jpeg/venue-logo.jpg'),
    pubName: 'Comedy Night',
    uploadTime: '4 days ago',
    place: 'The Venue, Manchester',
    date: 'Sat 15th Aug at 8pm',
    accepted: '2/2',
    exactDate: 'Sat 15th Aug',
    status: 'All set!',
    time: 'From 8pm to 11pm',
    description:
      ' Lorem ipsum dolor sit amet, consetetur sadipscing elitr, seddiam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et',
  },
  {
    id: 4,
    profileLogo: require('../../assets/Images/Jpeg/venue-logo.jpg'),
    pubName: 'Rooftop Open Mic',
    uploadTime: '10 days ago',
    place: 'The Venue, Manchester',
    date: 'Sat 15th Aug at 8pm',
    exactDate: 'Sat 15th Aug',
    accepted: '2/5',
    status: 'Recruiting',
    time: 'From 8pm to 11pm',
    description:
      ' Lorem ipsum dolor sit amet, consetetur sadipscing elitr, seddiam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et',
  },
  {
    id: 5,
    profileLogo: require('../../assets/Images/Jpeg/venue-logo.jpg'),
    pubName: 'Comedy Night',
    uploadTime: '2 days ago',
    place: 'The Venue, Manchester',
    date: 'Sat 15th Aug at 8pm',
    accepted: '0/2',
    exactDate: 'Sat 15th Aug',
    status: 'Recruiting',
    time: 'From 8pm to 11pm',
    description:
      ' Lorem ipsum dolor sit amet, consetetur sadipscing elitr, seddiam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et',
  },
  {
    id: 6,
    profileLogo: require('../../assets/Images/Jpeg/venue-logo.jpg'),
    pubName: 'Rooftop Open Mic',
    uploadTime: '1 days ago',
    place: 'The Venue, Manchester',
    date: 'Sat 15th Aug at 8pm',
    accepted: '3/5',
    exactDate: 'Sat 15th Aug',
    status: 'Recruiting',
    time: 'From 8pm to 11pm',
    description:
      ' Lorem ipsum dolor sit amet, consetetur sadipscing elitr, seddiam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et',
  },
  {
    id: 7,
    profileLogo: require('../../assets/Images/Jpeg/venue-logo.jpg'),
    pubName: 'Comedy Night',
    uploadTime: '5 days ago',
    place: 'The Venue, Manchester',
    date: 'Sat 15th Aug at 8pm',
    time: 'From 8pm to 11pm',
    accepted: '2/4',
    exactDate: 'Sat 15th Aug',
    status: 'Recruiting',
    description:
      ' Lorem ipsum dolor sit amet, consetetur sadipscing elitr, seddiam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et',
  },
];
