export const EventDataList = [
  {
    id: 1,
    image: require('../assets/Images/pubImages/01.jpeg'),
    name: 'Nuts Pub Crawl',
    uploadTime: '4 days ago',
    location: 'The Venue, Manchester',
    eventTime: 'Sat 15th Aug at 8pm',
    distance: '6 mi',
    remainingTime: '3 hr',
    timeTo: ' 8pm to 11pm',
    Amount: '£150',
    status: 'active',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Hic, eveniet corrupti ipsam, assumenda eaque ullam quibusdam quodunde corporis provident voluptate officia ipsa accusantium sintnulla sapiente. Iste, sunt perferendis?',
  },
  {
    id: 2,
    image: require('../assets/Images/pubImages/02.png'),
    name: 'The Armoury',
    uploadTime: '4 days ago',
    location: 'The Venue, Manchester',
    eventTime: 'Sat 15th Aug at 8pm',
    timeTo: ' 8pm to 11pm',
    distance: '10 km',
    remainingTime: '7 hr',
    Amount: '£200',
    status: 'active',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Hic, eveniet corrupti ipsam, assumenda eaque ullam quibusdam quodunde corporis provident voluptate officia ipsa accusantium sintnulla sapiente. Iste, sunt perferendis?',
  },
  {
    id: 3,
    image: require('../assets/Images/pubImages/03.jpeg'),
    uploadTime: '4 days ago',
    name: 'The Foo Fighters',
    location: 'The Venue, Manchester',
    eventTime: 'Sat 15th Aug at 8pm',
    distance: '5 mi',
    remainingTime: '3 hr',
    timeTo: ' 8pm to 11pm',
    Amount: '£100',
    status: 'Completed',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Hic, eveniet corrupti ipsam, assumenda eaque ullam quibusdam quodunde corporis provident voluptate officia ipsa accusantium sintnulla sapiente. Iste, sunt perferendis?',
  },
  {
    id: 4,
    image: require('../assets/Images/pubImages/04.png'),
    uploadTime: '4 days ago',
    name: 'The Tower',
    location: 'The Venue, Manchester',
    eventTime: 'Sat 15th Aug at 8pm',
    distance: '2 mi',
    remainingTime: '3 hr',
    timeTo: ' 8pm to 11pm',
    Amount: '£120',
    status: 'active',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Hic, eveniet corrupti ipsam, assumenda eaque ullam quibusdam quodunde corporis provident voluptate officia ipsa accusantium sintnulla sapiente. Iste, sunt perferendis?',
  },
  {
    id: 5,
    image: require('../assets/Images/pubImages/05.jpeg'),
    uploadTime: '4 days ago',
    name: 'Cheshire Cheese',
    location: 'The Venue, Manchester',
    eventTime: 'Sat 15th Aug at 8pm',
    distance: '2 mi',
    remainingTime: '3 hr',
    timeTo: ' 8pm to 11pm',
    Amount: '£180',
    status: 'Completed',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Hic, eveniet corrupti ipsam, assumenda eaque ullam quibusdam quodunde corporis provident voluptate officia ipsa accusantium sintnulla sapiente. Iste, sunt perferendis?',
  },
  {
    id: 6,
    image: require('../assets/Images/pubImages/06.jpg'),
    uploadTime: '4 days ago',
    name: 'Comedy Night',
    location: 'The Venue, Manchester',
    eventTime: 'Sat 15th Aug at 8pm',
    distance: '2 mi',
    remainingTime: '3 hr',
    timeTo: ' 8pm to 11pm',
    Amount: '£150',
    status: 'Completed',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Hic, eveniet corrupti ipsam, assumenda eaque ullam quibusdam quodunde corporis provident voluptate officia ipsa accusantium sintnulla sapiente. Iste, sunt perferendis?',
  },
  {
    id: 7,
    image: require('../assets/Images/pubImages/06.jpg'),
    uploadTime: '4 days ago',
    name: 'Comedy Night',
    location: 'The Venue, Manchester',
    eventTime: 'Sat 15th Aug at 8pm',
    distance: '2 mi',
    remainingTime: '3 hr',
    timeTo: ' 8pm to 11pm',
    Amount: '£130',
    status: 'active',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Hic, eveniet corrupti ipsam, assumenda eaque ullam quibusdam quodunde corporis provident voluptate officia ipsa accusantium sintnulla sapiente. Iste, sunt perferendis?',
  },
];
