export const ActiveList = [
  {
    id: 1,
    image: require('../assets/Images/pubImages/01.jpeg'),
    name: 'Nuts Pub Crawl',
    uploadTime: '4 days ago',
    location: 'The Venue, Manchester',
    eventTime: 'Sat 15th Aug at 8pm',
    eventDate: 'Sat 15th Aug',
    distance: '6 mi',
    remainingTime: '3 hr',
    Amount: '£150',
    curretStatus: 'active',
    status: 'In 2 days',
    timing: '8pm to 11pm',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Hic, eveniet corrupti ipsam, assumenda eaque ullam quibusdam quodunde corporis provident voluptate officia ipsa accusantium sintnulla sapiente. Iste, sunt perferendis?',
  },
  {
    id: 2,
    image: require('../assets/Images/pubImages/02.png'),
    name: 'The Armoury',
    uploadTime: '4 days ago',
    location: 'The Venue, Manchester',
    eventTime: 'Sat 15th Aug at 8pm',
    eventDate: 'Sat 15th Aug',
    distance: '1 km',
    remainingTime: '7 hr',
    Amount: '£200',
    status: 'active',
    status: 'Pending',
    timing: '8pm to 11pm',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Hic, eveniet corrupti ipsam, assumenda eaque ullam quibusdam quodunde corporis provident voluptate officia ipsa accusantium sintnulla sapiente. Iste, sunt perferendis?',
  },
  {
    id: 3,
    image: require('../assets/Images/pubImages/03.jpeg'),
    uploadTime: '4 days ago',
    name: 'The Foo Fighters',
    location: 'The Venue, Manchester',
    eventTime: 'Sat 15th Aug at 8pm',
    eventDate: 'Sat 15th Aug',
    distance: '5 mi',
    remainingTime: '3 hr',
    Amount: '£100',
    status: 'Completed',
    status: 'Position filled',
    timing: '8pm to 11pm',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Hic, eveniet corrupti ipsam, assumenda eaque ullam quibusdam quodunde corporis provident voluptate officia ipsa accusantium sintnulla sapiente. Iste, sunt perferendis?',
  },
];

export const CompletedList = [
  {
    id: 1,
    image: require('../assets/Images/pubImages/01.jpeg'),
    name: 'Nuts Pub Crawl',
    uploadTime: '4 days ago',
    location: 'The Venue, Manchester',
    eventTime: 'Sat 15th Aug at 8pm',
    eventDate: 'Sat 15th Aug',
    distance: '6 mi',
    remainingTime: '3 hr',
    Amount: '£150',
    curretStatus: 'Compeleted',
    status: 'Pending',
    timing: '8pm to 11pm',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Hic, eveniet corrupti ipsam, assumenda eaque ullam quibusdam quodunde corporis provident voluptate officia ipsa accusantium sintnulla sapiente. Iste, sunt perferendis?',
  },
  {
    id: 2,
    image: require('../assets/Images/pubImages/01.jpeg'),
    name: 'Nuts Pub Crawl',
    uploadTime: '4 days ago',
    location: 'The Venue, Manchester',
    eventTime: 'Sat 15th Aug at 8pm',
    eventDate: 'Sat 15th Aug',
    distance: '6 mi',
    remainingTime: '3 hr',
    Amount: '£150',
    curretStatus: 'Compeleted',
    status: 'Paid',
    timing: '8pm to 11pm',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Hic, eveniet corrupti ipsam, assumenda eaque ullam quibusdam quodunde corporis provident voluptate officia ipsa accusantium sintnulla sapiente. Iste, sunt perferendis?',
  },
  {
    id: 3,
    image: require('../assets/Images/pubImages/01.jpeg'),
    name: 'Nuts Pub Crawl',
    uploadTime: '4 days ago',
    location: 'The Venue, Manchester',
    eventTime: 'Sat 15th Aug at 8pm',
    eventDate: 'Sat 15th Aug',
    distance: '6 mi',
    remainingTime: '3 hr',
    Amount: '£150',
    curretStatus: 'Compeleted',
    status: 'Paid',
    timing: '8pm to 11pm',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Hic, eveniet corrupti ipsam, assumenda eaque ullam quibusdam quodunde corporis provident voluptate officia ipsa accusantium sintnulla sapiente. Iste, sunt perferendis?',
  },
];
